-- Création de la table lexique

DROP TABLE IF EXISTS lexiques;



CREATE TABLE lexiques (
    id BIGSERIAL PRIMARY KEY,
    mot VARCHAR(100) NOT NULL,
    definition TEXT NOT NULL,    
    created_by VARCHAR(64) DEFAULT 'SYSTEM',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(64) DEFAULT 'SYSTEM',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert de 300+ mots informatiques
INSERT INTO lexiques (mot, definition) VALUES
('API', 'Application Programming Interface : ensemble de règles permettant à des applications de communiquer.'),
('Algorithme', 'Suite d’instructions permettant de résoudre un problème ou d’effectuer une tâche.'),
('Backend', 'Partie serveur d’une application qui gère les données et la logique métier.'),
('Base de données', 'Système organisé pour stocker, gérer et récupérer des données.'),
('Bug', 'Défaut ou erreur dans un logiciel provoquant un comportement inattendu.'),
('Cloud', 'Serveurs distants sur Internet pour stocker et gérer des données.'),
('CI/CD', 'Continuous Integration / Continuous Deployment : automatisation des tests, intégration et déploiement du code.'),
('CSS', 'Cascading Style Sheets : langage de style pour formater l’apparence des pages web.'),
('DevOps', 'Pratiques combinant développement logiciel et opérations IT pour améliorer la livraison continue.'),
('DNS', 'Domain Name System : traduit les noms de domaine en adresses IP.'),
('Frontend', 'Partie visible d’une application avec laquelle l’utilisateur interagit.'),
('HTML', 'HyperText Markup Language : langage de balisage pour structurer une page web.'),
('HTTP', 'HyperText Transfer Protocol : protocole pour transférer des données sur le web.'),
('HTTPS', 'Version sécurisée de HTTP avec chiffrement SSL/TLS.'),
('JavaScript', 'Langage de programmation côté client pour rendre les pages web interactives.'),
('JSON', 'JavaScript Object Notation : format léger pour échanger des données entre applications.'),
('Middleware', 'Logiciel intermédiaire gérant la communication entre applications et serveurs.'),
('Microservices', 'Architecture découpant une application en services indépendants et spécialisés.'),
('Node.js', 'Environnement JavaScript côté serveur pour créer des applications réseau rapides.'),
('ORM', 'Object-Relational Mapping : technique qui relie objets et base de données relationnelle.'),
('Proxy', 'Serveur intermédiaire entre client et serveur pour filtrer ou cacher les requêtes.'),
('REST', 'Representational State Transfer : style d’architecture pour créer des API.'),
('SaaS', 'Software as a Service : logiciel accessible via Internet sans installation locale.'),
('SDK', 'Software Development Kit : ensemble d’outils pour développer des applications pour une plateforme.'),
('SEO', 'Search Engine Optimization : optimisation d’un site pour le référencement naturel.'),
('SQL', 'Structured Query Language : langage pour interroger et gérer des bases de données relationnelles.'),
('SSL', 'Secure Sockets Layer : protocole pour sécuriser les communications Internet.'),
('Token', 'Jeton numérique utilisé pour authentifier ou valider des transactions.'),
('UI', 'User Interface : interface utilisateur d’une application ou d’un site web.'),
('UX', 'User Experience : expérience globale de l’utilisateur lors de l’utilisation d’une application.'),
('Virtualisation', 'Création de ressources virtuelles à partir de ressources physiques.'),
('VPN', 'Virtual Private Network : réseau privé sécurisé sur Internet.'),
('WebSocket', 'Protocole pour communication bidirectionnelle en temps réel entre client et serveur.'),
('Versioning', 'Gestion des différentes versions d’un logiciel ou d’un document.'),
('Virtual DOM', 'Représentation en mémoire de l’interface pour optimiser le rendu dans des frameworks comme React.'),
('Container', 'Environnement isolé permettant d’exécuter une application avec toutes ses dépendances.'),
('Framework', 'Ensemble de bibliothèques et outils facilitant le développement d’applications.'),
('Git', 'Système de gestion de versions distribué pour suivre l’historique du code.'),
('GitHub', 'Plateforme hébergeant des projets Git et facilitant la collaboration.'),
('IDE', 'Integrated Development Environment : logiciel pour écrire, tester et déboguer du code.'),
('Java', 'Langage de programmation orienté objet utilisé côté serveur et client.'),
('Kotlin', 'Langage moderne pour JVM et Android, compatible avec Java.'),
('JSON Web Token', 'Format sécurisé pour transmettre des informations entre un client et un serveur.'),
('Kubernetes', 'Plateforme open-source pour orchestrer des containers à grande échelle.'),
('Laravel', 'Framework PHP pour développer rapidement des applications web.'),
('Machine Learning', 'Technique d’IA permettant à une machine d’apprendre à partir de données.'),
('MongoDB', 'Base de données NoSQL orientée documents.'),
('MySQL', 'Système de gestion de base de données relationnelle open-source.'),
('OAuth', 'Protocole d’autorisation sécurisé permettant à un utilisateur de donner accès à ses données.'),
('Open Source', 'Logiciel dont le code source est librement accessible et modifiable.'),
('PHP', 'Langage de programmation serveur pour créer des pages web dynamiques.'),
('Python', 'Langage polyvalent utilisé pour le web, la data science et l’IA.'),
('QA', 'Quality Assurance : ensemble des processus pour garantir la qualité d’un logiciel.'),
('React', 'Bibliothèque JavaScript pour créer des interfaces utilisateur dynamiques.'),
('React Native', 'Framework pour développer des applications mobiles multiplateformes avec React.'),
('Redux', 'Bibliothèque pour gérer l’état d’applications JavaScript complexes.'),
('RESTful', 'Style d’architecture d’API respectant les principes REST.'),
('Router', 'Composant ou service gérant la navigation entre pages d’une application web.'),
('Scrum', 'Méthode agile pour gérer des projets logiciels avec des itérations courtes.'),
('SQL Injection', 'Technique d’attaque exploitant les vulnérabilités d’une base de données via SQL.'),
('Serverless', 'Architecture où le fournisseur cloud gère automatiquement le serveur et l’exécution des fonctions.'),
('Spring Boot', 'Framework Java facilitant la création d’applications backend autonomes et prêtes à l’emploi.'),
('SSL/TLS', 'Protocoles pour sécuriser les communications sur Internet par chiffrement.'),
('Test Unitaire', 'Méthode de test consistant à vérifier le fonctionnement d’une unité de code isolée.'),
('Test d’Intégration', 'Test vérifiant l’interaction correcte entre plusieurs modules ou composants.'),
('UI/UX Design', 'Conception de l’interface utilisateur et de l’expérience globale pour les utilisateurs.'),
('URL', 'Uniform Resource Locator : adresse web permettant de localiser une ressource sur Internet.'),
('UX', 'User Experience : expérience et satisfaction globale de l’utilisateur lors de l’utilisation d’une application.'),
('Version Control', 'Système de gestion des versions du code pour suivre les modifications et collaborer efficacement.'),
('Virtual Machine', 'Environnement logiciel simulant un ordinateur physique pour exécuter des systèmes ou applications.'),
('Web API', 'Interface de programmation accessible via HTTP pour échanger des données avec une application web.'),
('Webhook', 'Mécanisme permettant à une application de recevoir automatiquement des notifications d’un service externe.'),
('WebAssembly', 'Format binaire permettant d’exécuter du code proche du natif dans le navigateur.'),
('YAML', 'Yet Another Markup Language : format de données lisible utilisé pour la configuration et les échanges.'),
('Big Data', 'Traitement et analyse de très grands volumes de données complexes.'),
('Blockchain', 'Base de données distribuée et sécurisée utilisée pour enregistrer des transactions.'),
('Bot', 'Programme automatisé qui effectue des tâches répétitives sur Internet.'),
('CDN', 'Content Delivery Network : réseau de serveurs pour distribuer du contenu plus rapidement.'),
('Cybersecurity', 'Ensemble de pratiques pour protéger les systèmes et données contre les cyberattaques.'),
('Data Lake', 'Réservoir centralisé pour stocker des données brutes de toutes sortes.'),
('Data Warehouse', 'Système centralisé pour stocker et organiser les données pour l’analyse.'),
('Docker', 'Plateforme pour créer, déployer et exécuter des applications dans des containers.'),
('Encryption', 'Processus de chiffrement des données pour les sécuriser contre les accès non autorisés.'),
('Firewall', 'Barrière de sécurité qui contrôle le trafic réseau entrant et sortant.'),
('GitLab', 'Plateforme Git pour héberger du code et gérer des projets DevOps.'),
('GraphQL', 'Langage de requête pour API permettant de demander exactement les données nécessaires.'),
('Hash', 'Fonction qui transforme des données en une chaîne fixe pour vérification ou sécurité.'),
('IoT', 'Internet of Things : objets connectés communiquant entre eux via Internet.'),
('JWT', 'JSON Web Token : standard pour transmettre des informations sécurisées entre parties.'),
('Load Balancer', 'Répartisseur de charge distribuant le trafic entre plusieurs serveurs.'),
('Multithreading', 'Exécution simultanée de plusieurs threads pour améliorer les performances.'),
('NoSQL', 'Bases de données non relationnelles adaptées aux grandes volumétries et aux données non structurées.'),
('Python Frameworks', 'Frameworks Python tels que Django, Flask pour le développement rapide d’applications.'),
('Responsive Design', 'Conception d’interfaces qui s’adaptent à différentes tailles d’écran.'),
('Selenium', 'Outil pour automatiser les tests de navigateurs web.'),
('SPA', 'Single Page Application : application web chargée sur une seule page pour une navigation fluide.'),
('SQL Server', 'Système de gestion de base de données relationnelle développé par Microsoft.'),
('TensorFlow', 'Bibliothèque open-source pour le Machine Learning et l’IA.'),
('TypeScript', 'Langage basé sur JavaScript avec typage statique, utilisé notamment avec Angular.'),
('Vue.js', 'Framework JavaScript pour créer des interfaces utilisateur réactives.'),
('Webpack', 'Module bundler pour compiler JavaScript et ressources front-end.'),
('Agile', 'Méthodologie de gestion de projet favorisant l’adaptabilité et les itérations rapides.'),
('Ansible', 'Outil open-source d’automatisation pour configuration et déploiement d’infrastructures.'),
('Apache', 'Serveur web open-source populaire pour héberger des sites web.'),
('Array', 'Structure de données contenant des éléments du même type.'),
('Artificial Intelligence', 'Ensemble de techniques permettant à des machines de simuler l’intelligence humaine.'),
('Authentication', 'Processus de vérification de l’identité d’un utilisateur ou d’un système.'),
('Authorization', 'Processus de contrôle des droits et accès aux ressources après authentification.'),
('Bandwidth', 'Capacité de transmission de données d’un réseau sur une période donnée.'),
('Binary', 'Système numérique utilisant uniquement 0 et 1 pour représenter les données.'),
('Bit', 'Unité de base de l’information informatique représentant 0 ou 1.'),
('Blockchain Node', 'Ordinateur participant au réseau blockchain pour valider et stocker les transactions.'),
('Bootstrap', 'Framework CSS pour créer rapidement des interfaces web responsives.'),
('Brute Force', 'Méthode d’attaque consistant à tester toutes les combinaisons possibles pour deviner un mot de passe.'),
('Cache', 'Mémoire temporaire pour stocker des données et accélérer les accès futurs.'),
('Captcha', 'Test de sécurité permettant de différencier un humain d’un robot.'),
('CI', 'Continuous Integration : pratique consistant à intégrer régulièrement le code pour détecter rapidement les erreurs.'),
('CLI', 'Command Line Interface : interface permettant de contrôler un logiciel via des commandes texte.'),
('Cluster', 'Groupe de serveurs travaillant ensemble pour augmenter la disponibilité et les performances.'),
('Compression', 'Réduction de la taille des fichiers pour optimiser stockage et transfert.'),
('Cookie', 'Petit fichier stocké sur l’ordinateur pour mémoriser des informations liées à l’utilisateur.'),
('Cross-Site Scripting', 'Attaque web permettant d’injecter du code malveillant dans une page web.'),
('Cryptography', 'Science et techniques pour sécuriser les communications et les données.'),
('CSS Grid', 'Système de mise en page CSS permettant d’organiser les éléments en grille.'),
('CSS Flexbox', 'Module CSS pour créer des mises en page flexibles et adaptatives.'),
('Data Mining', 'Extraction de connaissances à partir de grandes quantités de données.'),
('Data Science', 'Domaine combinant statistiques, informatique et analyse pour exploiter les données.'),
('Database Index', 'Structure de données qui accélère la recherche et l’accès aux informations en base.'),
('Debugging', 'Processus de recherche et correction des erreurs dans le code.'),
('Deep Learning', 'Sous-ensemble du Machine Learning utilisant des réseaux neuronaux profonds.'),
('Deployment', 'Processus de mise en production d’une application ou d’une mise à jour.'),
('DNS Record', 'Entrée dans le système DNS permettant de relier un nom de domaine à une ressource.'),
('Docker Compose', 'Outil pour définir et gérer des applications multi-containers Docker.'),
('DOM', 'Document Object Model : structure représentant le contenu d’une page web.'),
('Domain', 'Nom qui identifie un site web sur Internet.'),
('Encryption Key', 'Clé utilisée pour chiffrer et déchiffrer des informations sécurisées.'),
('Firewall Rules', 'Ensemble de règles configurées pour contrôler le trafic réseau.'),
('Git Branch', 'Version parallèle du code permettant de développer des fonctionnalités séparément.'),
('Git Commit', 'Action d’enregistrer des modifications dans l’historique du code.'),
('Git Merge', 'Action de fusionner les modifications de différentes branches de code.'),
('Graph Database', 'Base de données utilisant des graphes pour représenter les relations entre données.'),
('GUI', 'Graphical User Interface : interface utilisateur graphique.');
